document.write("<footer id=\"footer\">");
document.write("	<section>");
document.write("		<ul class=\"icons\">");
document.write("			<li><a href=\"mailto:wlab@wlab.pro\" class=\"icon fa-envelope alt\" target=\"_blank\"><span class=\"label\">Email<\/span><\/a><\/li>");
document.write("			<li><a href=\"https:\/\/github.com\/wlab-pro\" class=\"icon fa-github alt\" target=\"_blank\"><span class=\"label\">GitHub<\/span><\/a><\/li>");
document.write("			<li><a href=\"#\" class=\"icon fa-youtube alt\" target=\"_blank\"><span class=\"label\">Youtube<\/span><\/a><\/li>");
document.write("			<li><a href=\"#\" class=\"icon fa-facebook alt\" target=\"_blank\"><span class=\"label\">Facebook<\/span><\/a><\/li>");
document.write("			<li><a href=\"#\" class=\"icon fa-twitter alt\" target=\"_blank\"><span class=\"label\">Twitter<\/span><\/a><\/li>");
document.write("		<\/ul>");
document.write("	<\/section>");
document.write("	<p class=\"copyright\">Copyright &copy; <a href=\"https:\/\/wlab.pro\">WLab<\/a> | Designed by <a href=\"https:\/\/html5up.net\">HTML5 UP<\/a>.<\/p>");
document.write("<\/footer>");
document.write("");
