document.write('<meta charset="utf-8" />');
document.write('<meta name="viewport" content="width=device-width, initial-scale=1" />');
document.write('<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->');
document.write('<link rel="stylesheet" href="assets/css/main.css" />');
document.write('<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->');
document.write('<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->');

document.write('<link rel="apple-touch-icon" sizes="57x57" href="favicons/apple-touch-icon-57x57.png">');
document.write('<link rel="apple-touch-icon" sizes="60x60" href="favicons/apple-touch-icon-60x60.png">');
document.write('<link rel="apple-touch-icon" sizes="72x72" href="favicons/apple-touch-icon-72x72.png">');
document.write('<link rel="apple-touch-icon" sizes="76x76" href="favicons/apple-touch-icon-76x76.png">');
document.write('<link rel="apple-touch-icon" sizes="114x114" href="favicons/apple-touch-icon-114x114.png">');
document.write('<link rel="apple-touch-icon" sizes="120x120" href="favicons/apple-touch-icon-120x120.png">');
document.write('<link rel="apple-touch-icon" sizes="144x144" href="favicons/apple-touch-icon-144x144.png">');
document.write('<link rel="apple-touch-icon" sizes="152x152" href="favicons/apple-touch-icon-152x152.png">');
document.write('<link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon-180x180.png">');
document.write('<link rel="icon" type="image/png" href="favicons/favicon-32x32.png" sizes="32x32">');
document.write('<link rel="icon" type="image/png" href="favicons/favicon-194x194.png" sizes="194x194">');
document.write('<link rel="icon" type="image/png" href="favicons/android-chrome-192x192.png" sizes="192x192">');
document.write('<link rel="icon" type="image/png" href="favicons/favicon-16x16.png" sizes="16x16">');
document.write('<link rel="manifest" href="favicons/manifest.json">');
document.write('<link rel="mask-icon" href="favicons/safari-pinned-tab.svg" color="#8cc9f0">');
document.write('<link rel="shortcut icon" href="favicons/favicon.ico">');
document.write('<meta name="msapplication-TileColor" content="#9f00a7">');
document.write('<meta name="msapplication-TileImage" content="favicons/mstile-144x144.png">');
document.write('<meta name="msapplication-config" content="favicons/browserconfig.xml">');
document.write('<meta name="theme-color" content="#ffffff">');
