document.write(
  '<meta charset="utf-8" />\n'
+ '<meta name="viewport" content="width=device-width, initial-scale=1" />\n'
+ '<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->\n'
+ '<link rel="stylesheet" href="assets/css/main.css" />\n'
+ '<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->\n'
+ '<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->\n'
+ '\n'
+ '<link rel="apple-touch-icon" sizes="57x57" href="favicons/apple-touch-icon-57x57.png">\n'
+ '<link rel="apple-touch-icon" sizes="60x60" href="favicons/apple-touch-icon-60x60.png">\n'
+ '<link rel="apple-touch-icon" sizes="72x72" href="favicons/apple-touch-icon-72x72.png">\n'
+ '<link rel="apple-touch-icon" sizes="76x76" href="favicons/apple-touch-icon-76x76.png">\n'
+ '<link rel="apple-touch-icon" sizes="114x114" href="favicons/apple-touch-icon-114x114.png">\n'
+ '<link rel="apple-touch-icon" sizes="120x120" href="favicons/apple-touch-icon-120x120.png">\n'
+ '<link rel="apple-touch-icon" sizes="144x144" href="favicons/apple-touch-icon-144x144.png">\n'
+ '<link rel="apple-touch-icon" sizes="152x152" href="favicons/apple-touch-icon-152x152.png">\n'
+ '<link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon-180x180.png">\n'
+ '<link rel="icon" type="image/png" href="favicons/favicon-32x32.png" sizes="32x32">\n'
+ '<link rel="icon" type="image/png" href="favicons/favicon-194x194.png" sizes="194x194">\n'
+ '<link rel="icon" type="image/png" href="favicons/android-chrome-192x192.png" sizes="192x192">\n'
+ '<link rel="icon" type="image/png" href="favicons/favicon-16x16.png" sizes="16x16">\n'
+ '<link rel="manifest" href="favicons/manifest.json">\n'
+ '<link rel="mask-icon" href="favicons/safari-pinned-tab.svg" color="#8cc9f0">\n'
+ '<link rel="shortcut icon" href="favicons/favicon.ico">\n'
+ '<meta name="msapplication-TileColor" content="#9f00a7">\n'
+ '<meta name="msapplication-TileImage" content="favicons/mstile-144x144.png">\n'
+ '<meta name="msapplication-config" content="favicons/browserconfig.xml">\n'
+ '<meta name="theme-color" content="#ffffff">\n'
);
